### PR TITLE
added svg's for jan 4x4

### PR DESCRIPTION
**Pull request by ajdema**
added, white, black, pieces and board svg

### CODE REVIEW

**Review by BnjmnZmmrmn — CHANGES_REQUESTED** [review]
**requested changes**
- jan is 4x4. board svg is 3x3
- there is no background for board svg, i.e boxes have no content
- board dimensions are 800 x 800 while piece dimensions are 128 x 128. even with 4x4 board, do we want pieces bigger than boxes?

**Comment by ajdema** [comment]
- The board looks like it's 3x3 but the pieces go on the corners/intersections so it's actually 4x4 checkout the [ludii board](https://ludii.games/details.php?keyword=A%20Simple%20Game) to see. 
- I can add a background if we want one. 
- I think we want a bit of space between adjacent pieces which is how I landed on the 800:128 ratio but I figured we could see how it feels to play and change it later—it's a simple change in the svg file.

**Comment by BnjmnZmmrmn** [comment]
> the pieces go on the corners/intersections so it's actually 4x4

sg i see what you mean

> I can add a background if we want one.

sure yeah we dont need yet

> we want a bit of space between adjacent pieces

yeah this is my concern too. sg to 800:128 but my concern was with the svg being 800x800 despite the internal board not meeting the boundaries of the file. also, i think the boxes are uneven in dimension.

**Comment by BnjmnZmmrmn** [comment]
> yeah this is my concern too. sg to 800:128 but my concern was with the svg being 800x800 despite the internal board not meeting the boundaries of the file. also, i think the boxes are uneven in dimension.

this matters for autogui json data

**Comment by BnjmnZmmrmn** [comment]
still not symmetrical boxes? i know we can update svgs later, but we at least need accurate pixels for the json data (centers)

**Review by BnjmnZmmrmn — APPROVED** [review]
money. we can always update pieces and background later during testing, but this should work for now. thanks!

**Pull request merged**
